### ISSUE TITLE
Bad components name

### ISSUE THREAD

**Issue by limelect** [jacek-mulawka/Mahjong-3D-z-Eris-Kallisti-Dyskordia#1]
If your components name is not in my English language
Delphi does not load the DFM properly and the form is missing 
those components.!!!!
Revert to English on your computer, and load again.

**Comment by jacek-mulawka** [comment]
Hi! Interesting... but OK, I renamed for you and uploaded to the directory 'Others' files 'Mahjong_3D for limelect.pas' and 'Mahjong_3D for limelect.dfm'. That makes that the translations files will not work completely so if you wish to use the translations please just change the local characters in the translation files. Greetings and good luck!

**Comment by limelect** [comment]
Thanks but impossible to use. See "raw".
I tried but it will take too much time to translate.
So I guess I am not the only one. 
If you want anyone to have fun with your software do it in ENGLISH.
As for the exe I do not get any because of viruses.
So for the time being, I pass. Good luck

**Comment by jacek-mulawka** [comment]
Thank you for the feedback.

About the raw:
if to change the code page in a web browser it shows correctly (I have the same).

About English:
if I do not have to work 'commercial' easier and faster is for me to use Polish, sorry for that.

After download the files seems fine and compile correctly so you should be able to create own executable file without problems.

Good day for you!

**Comment by limelect** [comment]
Your computer is Polish. Very simple.
Who has only English your fonts are jibberish

**Comment by jacek-mulawka** [comment]
Thank you for the opinion and the point of view. It is not good that your system do not support local characters, maybe you will be able to find a way to repair somehow your system. Keep coding, keep enjoying, keep smiling, good luck.

PS How about this limelect:

procedure TForm1.Button1Click( Sender: TObject );

  procedure 猫のおもちゃ( 量 : integer );
  begin

    ShowMessage( '一二三 は ' + IntToStr( 量 ) + ' です。' );

  end;

var
  木_1,
  木_2
    : integer;
  森 : boolean;
begin

  木_1 := 1;
  木_2 := 2;
  inc( 木_1 );

  if 木_1 + 木_2 > 3 then
    森 := true
  else
    森 := false;

  猫のおもちゃ( 木_1 + 木_2 );

end;

Greetings!
